NUMBER_OF_BASIC_STATS = 39
NUMBER_OF_BASIC_STATS_NOT_TO_AVERAGE = 10
INDEX_OF_BACK_TO_BACK_INFO = 9

INDEX_OF_FIRST_STAT_TO_ADD_TO_NEURAL_NETWORK = 11


INDEX_OF_NEURAL_NETWORK_GAME_NUMBER = 0
INDEX_OF_NEURAL_NETWORK_DATE = 1
INDEX_OF_NEURAL_NETWORK_HOME_OR_AWAY = 2
INDEX_OF_NEURAL_NETWORK_OPPONENT = 3
INDEX_OF_NEURAL_NETWORK_RESULT_STRAIGHT_UP = 4
INDEX_OF_NEURAL_NETWORK_RESULT_AGAINST_THE_SPREAD = 5
INDEX_OF_NEURAL_NETWORK_SPREAD = 6
INDEX_OF_NEURAL_NETWORK_OVER_UNDER_RESULT = 7
INDEX_OF_NEURAL_NETWORK_OVER_UNDER_LINE = 8